version: '3'

vars:
  CLIENT: '{{.CLIENT | default "eh"}}'
  ENV: '{{.ENV | default "dev"}}'
  TYPE: '{{.TYPE | default "schema"}}'
  COUNT: '{{.COUNT | default "1"}}'
  REPO: '{{.REPO | default "RepoA"}}'

tasks:
  liquibase-validate:
    desc: Run Liquibase validations
    cmds:
      - cd ./database/{{.CLIENT}}/{{.TYPE}} && liquibase --defaults-file=liquibase-{{.ENV}}.properties validate

  liquibase-migrate:
    desc: Run Liquibase migrations
    deps: [check-safe]
    cmds:
      - cd ./database/{{.CLIENT}}/{{.TYPE}} && liquibase --defaults-file=liquibase-{{.ENV}}.properties update

  liquibase-migrate-multi:
    desc: Run Liquibase migrations for stg, dev, prod
    cmds:
      - cd ./database/{{.CLIENT}}/data && liquibase --defaults-file=liquibase-prod.properties update
      - cd ./database/{{.CLIENT}}/data && liquibase --defaults-file=liquibase-stg.properties update
      - cd ./database/{{.CLIENT}}/data && liquibase --defaults-file=liquibase-dev.properties update

  liquibase-history:
    desc: Get Liquibase history
    cmds:
      - cd ./database/{{.CLIENT}}/{{.TYPE}} && liquibase --defaults-file=liquibase-{{.ENV}}.properties history

  check-safe:
    desc: Ensure latest DB state before rollback/migrate
    cmds:
      - |
        cd ./database/{{.CLIENT}}/{{.TYPE}} && (
          echo "📜 Generating Liquibase history..."
          liquibase --defaults-file=liquibase-{{.ENV}}.properties history > temp_history.txt
          python ../../../database/check-rollback-safety.py temp_history.txt {{.COUNT}}
        )

  liquibase-rollback:
    desc: Rollback Liquibase changes (safely)
    deps: [check-safe]
    cmds:
      - cd ./database/{{.CLIENT}}/{{.TYPE}} && liquibase.bat --defaults-file=liquibase-{{.ENV}}.properties rollbackCount {{.COUNT}}

  liquibase-clean:
    desc: Drop all objects
    cmds:
      - cd ./database/{{.CLIENT}}/schema && liquibase --defaults-file=liquibase-{{.ENV}}.properties dropAll
